run:
  dataset: ubuntu_irc              # or movie_dialogue
  split: dev                      # train/dev/test (as applicable)
  chunk_size: 50                   # Ubuntu IRC protocol
  seed: 0

model:
  provider: openai                    # or anthropic
  name: gpt-5-mini                    # or claude-sonnet-4-20250514
  temperature: 0
  max_tokens: 64                  # adjust per prompt
  structured_outputs: true         # JSON-only outputs for core methods

paths:
  data_dir: ./data/raw
  processed_dir: ./data/processed
  results_dir: ./data/results
  prompts_dir: ./prompts

eval:
  metrics: [nmi, ari, shen_f, vi, one_to_one, exact_p, exact_r, exact_f]
  report_json: true
  report_csv: true