run:
  method: direct_assignment        # or best_response / self_critic
  dataset: ubuntu_irc              # or movie_dialogue
  split: test                      # train/dev/test (as applicable)
  chunk_size: 50                   # Ubuntu IRC protocol
  seed: 0

model:
  provider: openai
  name: gpt-4o-mini                     # or gpt-4o-mini
  temperature: 0
  max_tokens: 32                  # adjust per prompt
  structured_outputs: true         # JSON-only outputs for core methods

paths:
  data_dir: ./data/raw
  processed_dir: ./data/processed
  results_dir: ./data/results
  prompts_dir: ./prompts

eval:
  metrics: [nmi, ari, shen_f]
  report_json: true
  report_csv: true