run:
  dataset: ubuntu_irc
  split: dev
  chunk_size: 50
  seed: 0

model:
  provider: openai
  name: gpt-5-mini
  temperature: 0
  max_tokens: 64
  structured_outputs: true
  reasoning_effort: medium

paths:
  data_dir: ./data/raw
  processed_dir: ./data/processed
  results_dir: ./data/results_ensemble/br-da-6-gpt-5
  prompts_dir: ./prompts

eval:
  metrics: [nmi, ari, shen_f, vi, one_to_one, exact_p, exact_r, exact_f]
  report_json: true
  report_csv: true

ensemble:
  structure_predictions: ./data/results/jonathans_models/dev/predictions-structure-dev.jsonl
  ff_predictions: ./data/results/jonathans_models/dev/predictions-ff-dev.jsonl
  best_response_predictions: ./data/results_batch/best_response/predictions.jsonl
  direct_assignment_predictions: ./data/results/direct_assignment/dev/predictions.jsonl
  threshold_ff_predictions: ./data/results/jonathans_models/dev/predictions-threshold-ff-dev.jsonl
  br_runs:
    - ./data/results_batch/best_response/predictions-run1.jsonl
    - ./data/results_batch/best_response/predictions-run2.jsonl
    - ./data/results_batch/best_response/predictions-run3.jsonl
  da_runs:
    - ./data/results/direct_assignment/dev/predictions-run1.jsonl
    - ./data/results/direct_assignment/dev/predictions-run2.jsonl
    - ./data/results/direct_assignment/dev/predictions-run3.jsonl
