run:
  dataset: ubuntu_irc              
  split: dev                      # train/dev/test (as applicable)
  chunk_size: 50                   # Ubuntu IRC protocol
  seed: 0

model:
  provider: openai
  name: gpt-5
  temperature: 0
  max_tokens: 64                  # adjust per prompt
  structured_outputs: true         # JSON-only outputs for core methods

paths:
  data_dir: ./data/raw
  processed_dir: ./data/subsets
  results_dir: ./data/results_subset
  prompts_dir: ./prompts

eval:
  metrics: [nmi, ari, shen_f, vi, one_to_one, exact_p, exact_r, exact_f]
  report_json: true
  report_csv: true